set -g default-terminal "xterm"

set -g status-style "bg=black, fg=yellow"
set -wg window-status-current-style "fg=red"

set -g base-index 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

run -b '~/.tmux/plugins/tpm/tpm'
tmux new-window -c "#{pane_current_path}"
set-option -g default-path "#{pane_current_path}"

# support git branch name in tmux status bar.
set -g status-right-length 100
set -g status-right '#[fg=colour117] #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "no-git") #[fg=colour244]| %Y-%m-%d %H:%M#[default]'

# make session name full display.
set -g status-left-length 60
set -g status-left '#[fg=colour148,bold][#S]#[default] '
